-- SUPABASE SCHEMA FOR MTL FEEDBACK PLAYGROUND
-- Run this once in the Supabase SQL editor before saving playground runs.

CREATE TABLE IF NOT EXISTS public."MTL_PLAYGROUND_FEEDBACK" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id UUID NOT NULL,
  teacher_email TEXT,
  essay_title TEXT NOT NULL DEFAULT '',
  essay_description TEXT NOT NULL DEFAULT '',
  writing_text TEXT NOT NULL DEFAULT '',
  ai_prompt TEXT NOT NULL DEFAULT '',
  model TEXT NOT NULL,
  feedback_text TEXT NOT NULL DEFAULT '',
  feedback_json JSONB,
  request_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS mtl_playground_feedback_teacher_created_idx
  ON public."MTL_PLAYGROUND_FEEDBACK"(teacher_id, created_at DESC);

ALTER TABLE public."MTL_PLAYGROUND_FEEDBACK" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Teachers manage own MTL playground runs"
  ON public."MTL_PLAYGROUND_FEEDBACK";

CREATE POLICY "Teachers manage own MTL playground runs"
  ON public."MTL_PLAYGROUND_FEEDBACK"
  FOR ALL
  USING (teacher_id = auth.uid())
  WITH CHECK (teacher_id = auth.uid());
